Repository openedx/frontend-app-learner-record, pull requests merged in 2024-02, with the labels that each got.

#257 refactor: replace @edx/paragon and @edx/frontend-build
  .eslintrc.js
  jest.config.js
  module.config.js.example
  package-lock.json
  package.json
  patches/@openedx+frontend-build+13.0.28.patch
  src/components/NavigationBar/NavigationBar.jsx
  src/components/ProgramCertificate/ProgramCertificate.jsx
  src/components/ProgramCertificateModal/ProgramCertificateModal.jsx
  src/components/ProgramCertificatesList/ProgramCertificatesList.jsx
  src/components/ProgramRecord/ProgramRecord.jsx
  src/components/ProgramRecord/ProgramRecordActions.jsx
  src/components/ProgramRecord/ProgramRecordHeader.jsx
  src/components/ProgramRecord/ProgramRecordTable.jsx
  src/components/ProgramRecord/RecordsHelp.jsx
  src/components/ProgramRecordAlert/ProgramRecordAlert.jsx
  src/components/ProgramRecordSendModal/SendLearnerRecordModal.jsx
  src/components/ProgramRecordsList/ProgramRecordsList.jsx
  src/i18n/index.js
  src/index.scss
Labels: waiting on author, waiting for eng review, needs maintainer attention

#276 feat: Add a fluid container to allow for limiting the maximum width of the content
  src/components/ProgramCertificatesList/ProgramCertificatesList.jsx
  src/components/ProgramRecordsList/ProgramRecordsList.jsx
Labels: waiting on author, open-source-contribution

#277 feat: Add a fluid container to allow for limiting the maximum width of the content [backport from master]
  src/components/ProgramCertificatesList/ProgramCertificatesList.jsx
  src/components/ProgramRecordsList/ProgramRecordsList.jsx
Labels: open-source-contribution, backport
